# Generated by Django 4.0.5 on 2022-07-31 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('политика', 'политика'), ('бизнес', 'бизнес'), ('спорт', 'спорт'), ('мода', 'мода'), ('путешествия', 'путешествия')], default='политика', max_length=20)),
                ('image', models.ImageField(blank=True, default='static/images/none.jpg', null=True, upload_to='static/images/')),
                ('alt_image', models.CharField(max_length=50)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
