# Generated by Django 4.0.5 on 2022-08-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_active',
            field=models.BooleanField(default=True),
        ),
    ]
